### PR TITLE
ENH adds argparse constants

### PR DESCRIPTION
**Pull request by SantiagoTorres**
This adds the following functions:
- Adds **--force** to override the refresh times (good for testing)
- Adds **--info** to show information about the currently downloaded image

### CODE REVIEW

**Comment by SantiagoTorres** [comment]
@ElDeveloper could you take a look? thanks!

**Comment by ElDeveloper** [comment]
Code looks good, but I need to test in my system.

**Comment by ElDeveloper** [comment]
Following up on our conversation from last week, I still see nothing when I run `background_daemon.py --info`

**Comment by SantiagoTorres** [comment]
On Wed, Jun 22, 2016 at 07:00:49AM -0700, Yoshiki Vázquez Baeza wrote:

> Following up on our conversation from last week, I still see nothing when I run `background_daemon.py --info`

Can you give me more information?

Did you reinstall? how are you running it? which configuration is it
loading? Did you add a path? 

It seems to work on both of my systems.

**Comment by ElDeveloper** [comment]
👍

**Pull request merged**
